### ISSUE TITLE
我使用打包安装方式跟直接启动方式，前端都报错Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'join')

### ISSUE THREAD

**Issue by qq80284445** [ischenliang/quickly-picture-bed#36]
我使用打包安装方式跟直接启动方式，前端都报错Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'join')
而且打包也会报错：The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
vite v5.0.12 building for production...
✓ 1236 modules transformed.
Could not resolve "../userinfo/images/#U5b66#U751f#U5361#U901a_1.png?url" from "src/views/chatgpt/index.vue?vue&type=script&setup=true&lang.ts"
file: /home/www/node_project/upimg/client/src/views/chatgpt/index.vue?vue&type=script&setup=true&lang.ts
error during build:
RollupError: Could not resolve "../userinfo/images/#U5b66#U751f#U5361#U901a_1.png?url" from "src/views/chatgpt/index.vue?vue&type=script&setup=true&lang.ts"
    at error (file:///home/www/node_project/upimg/client/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at ModuleLoader.handleInvalidResolvedId (file:///home/www/node_project/upimg/client/node_modules/rollup/dist/es/shared/node-entry.js:18022:24)
    at file:///home/www/node_project/upimg/client/node_modules/rollup/dist/es/shared/node-entry.js:17982:26

**Comment by qq80284445** [comment]
这是不打包直接运行访问提示
main.ts:29 [Vue Router warn]: No match found for location with path "/"
App.vue:32 command + shift + p
config.ts:45 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'join')
    at config.ts:45:29
﻿
